[package]
name = "blish"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "*"
serde = "*"
serde_derive = "*"
lliw = "*"
tokio = { version = "1", features = ["full"] }
termion = "*"
